# Generated by Django 3.2 on 2021-04-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automato',
            name='diagrama',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
